Foodtopia/Controllers/RestaurantsController.cs
using Authentication.Common;
using Foodtopia.Common.Attribute;
using Foodtopia.Common.Controllers;
using Microsoft.AspNetCore.Mvc;
using RepositoryService.Interface;

namespace Foodtopia.Controllers
{
    [TypeFilter(typeof(Grant), Arguments = new object[] { AuthorizeLevel.AllowAnanymos, GrantPriority.Override })]
    public class RestaurantsController : BaseController
    {
        private readonly IFoodRepository _food;
        private readonly IRestaurantFoodRepository _restaurantFood;
        private readonly IRestaurantRepository _restaurant;
        private readonly IFoodCategoryRepository _foodCategory;
        private readonly IFoodTypeRepository _foodType;

        public RestaurantsController(IFoodTypeRepository foodType, IFoodCategoryRepository foodCategory, IRestaurantRepository restaurant, IRestaurantFoodRepository restaurantFood, IFoodRepository food)
        {
            _foodType = foodType;
            _foodCategory = foodCategory;
            _restaurant = restaurant;
            _restaurantFood = restaurantFood;
            _food = food;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Menu(int restaurantId)
        {
            return View();
        }
    
        public IActionResult Details(int restaurantId)
        {
            return View();
        }

    }
}

Foodtopia/Views/Shared/Components/RestaurantsList/Default.cshtml
@model IEnumerable<DataAccess.Model.Restaurant>

<div class="row">
    @{
        foreach (var restaurant in Model)
        {
            <div class="col-md-6 col-lg-3 ftco-animate">
                <div class="staff">
                    <a href="@Url.Action("Menu", "Restaurants", new {Area = "", id = restaurant.Id})">
                        <img class="img col-lg-12 col-xl-12 col-md-12 d-lg-block d-xl-block d-md-block d-sm-none d-none" src="..@restaurant.BannerImageAddress"/>
                        <img class="img d-lg-none d-xl-none d-md-none col-sm-8 col-8" src="..@restaurant.AvaterImageAddress"/>
                    </a>

                    <div class="text pt-4">
                        <h3 class="text-center">
                            <a href="@Url.Action("Menu", "Restaurants", new {Area = "", id = restaurant.Id})">@restaurant.Title</a>
                        </h3>
                        <span class="position mb-2">
                            <a href="@Url.Action("Menu", "Restaurants", new {Area = "", id = restaurant.Id})">@restaurant.Title</a>
                        </span>
                        <div class="faded">
                            <ul class="ftco-social d-flex">

                                @{
                                    if (restaurant.ShowRate)
                                    {
                                        <li class="ftco-animate">
                                            @{
                                                int i;
                                                for (i = 1; i <= restaurant.RateScore; i++)
                                                {
                                                    <i class="fas fa-star"></i>
                                                }

                                                if (i - restaurant.RateScore >= 0.5F && i - restaurant.RateScore < 1)
                                                {
                                                    <i class="fad fa-star-half-alt"></i>
                                                    i++;
                                                }

                                                for (; i < 5; i++)
                                                {
                                                    <i class="far fa-star"></i>
                                                }
                                            }
                                        </li>
                                    }
                                }
                                
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>